# Generated by Django 2.0.7 on 2021-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210224_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
