# Generated by Django 2.0.7 on 2021-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210302_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
