# Generated by Django 2.0.7 on 2021-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_uploaded_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uploaded_videos',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='exercises',
            field=models.TextField(default=None),
        ),
    ]
