# Generated by Django 2.0.7 on 2021-02-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='the_movie',
            new_name='movie',
        ),
    ]
