# Generated by Django 2.0.7 on 2021-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210228_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='movie',
        ),
        migrations.AddField(
            model_name='film',
            name='movie_url',
            field=models.URLField(default=None),
        ),
    ]
