# Generated by Django 2.0.7 on 2021-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_film_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_date',
            field=models.DateField(auto_now=True),
        ),
    ]
