# Generated by Django 2.0.7 on 2021-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_file',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
