# Generated by Django 2.0.7 on 2021-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exername', models.CharField(max_length=100)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='student_exer',
        ),
        migrations.DeleteModel(
            name='teacher_exer',
        ),
    ]
