# Generated by Django 2.0.7 on 2021-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_file_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
