# Generated by Django 2.0.7 on 2021-02-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20210224_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_exer',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercises.exercise')),
            ],
            bases=('exercises.exercise',),
        ),
        migrations.CreateModel(
            name='teacher_exer',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercises.exercise')),
            ],
            bases=('exercises.exercise',),
        ),
    ]
