# Generated by Django 2.0.7 on 2021-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20210228_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
