# Generated by Django 2.0.7 on 2021-02-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_student_exer_teacher_exer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exername',
            new_name='exercise_name',
        ),
    ]
