# Generated by Django 2.0.7 on 2021-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
