# Generated by Django 2.0.7 on 2021-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20210225_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
