# Generated by Django 2.0.7 on 2021-02-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20210225_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_name',
            new_name='name',
        ),
    ]
