# Generated by Django 2.0.7 on 2021-02-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20210225_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='exercise_name',
        ),
    ]
