# Generated by Django 2.0.7 on 2021-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='anonymous student', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
