# Generated by Django 2.0.7 on 2021-02-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210228_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='student',
            name='videos_to_watch',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
