# Generated by Django 2.0.7 on 2021-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', max_length=100)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('student_number', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
            ],
        ),
    ]
